Atest: fix NoneType of atest_unittest.py.
This is a porting of aosp/1200598.
Running unit tests will seldom encounter flaky test failure:
  self.assertTrue(data_time)
  AssertionError: None is not true
tempfile.mkdkdtemp() generates hashed filename which contains "_" so the
previous parsing would be faulty when the string is YYYYMMDD_HHMM__<hash>

Bug: 147202893

Test: source build/envsetup.sh; lunch
  croot tools/asuite/atest
  ./run_atest_unittests.sh # won't see issue of the bug.
  ./atest_run_unittests.py @ won't see issue of the bug.

Change-Id: I0dd8da0f0e6cf70a010037f15794f59deb36869f