Allow users to pass tracking config file.
Still default to storing tracking in
$HOME/.config/asuite/adevice-tracking.json, but also allow users to pass
their own config.

Test:  adevice --config foo.json track SomeModule && cat foo.json
Test: adevice --config foo.json status  # expected error on invalid module

 This works
Test: (unset HOME adevice status --verbose debug)

 This fails because there is no config.
Test: (unset HOME; adevice track the_wolf --verbose debug)
  Error: Can not save config file is HOME not set and --config not set.

Test: (unset HOME; adevice --config=some.json track HelloWorldHostTest  --verbose debug)
Test: adevice track FakeOemFeatures && adevice status && adevice untrack FakeOemFeatures
Bug: 302550378
Change-Id: I1025fee920ee6c76b66a7ac52eb5b00254abb18c