AIDEGen: fix potential failure of unit tests shell script.
In some cases the aidegen unit tests fail because of the order of library paths, this CL reordered PYTHONPATH by inserting ASUITE_DIR before ATEST_DIR, though in most cases the order does not affect the test result.

Bug: 161085170
Test: 1. source ./build/envsetup.sh && lunch 13
      2. cd tools/asuite/aidegen
      3. ./run_tests.sh
         without error message like ”AttributeError: partially initialized module 'aidegen.lib.common_util'
	 has no attribute 'back_to_cwd' (most likely due to a circular import)“
Change-Id: I8816ed67d8cc433e635b8891ae05b0759077a03f