AIDEGen: fake modules in module-info.json without path cause AIDEGen crash bug
Bug: 121101409
Test: 1. $ m aidegen
      2. $ ANDROID_HOST_OUT/bin/aidegen com.android.runtime
      3. AIDEGen should raise FakeModuleError
         aidegen.lib.errors.FakeModuleError: com.android.runtime is a fake module.
      4. $ ./run_tests.sh
         Test cases all passed!

Change-Id: I282dea27934e7279bd2f25069308e0923225a97b