AIDEGen: Fix 'cannot find module_bp_java_deps.json' issue.
build/make/core/main.mk:13: Calling make directly is no longer
supported. Because build system no longer supports make directly,
we change to use atest build method to generate the
module_bp_java_deps.json.

Bug: 138129456
Test: 1. m clean && m aidegen
         cd ./tools/tradefederation/core/
         aidegen-dev
         IntelliJ will be launched to open core project.
      2. aidegen-dev -a
         IntelliJ will be launched to open the whole tree
         as a project.

Change-Id: I2887886aefb97b9611b6654a978e061746859439